name: Build rule sets
on:
  push:
  workflow_run:
    workflows: "Update subnets"
    types: completed

permissions:
  contents: write

jobs:
  linux-build:
    runs-on: ubuntu-latest
    steps:
      - name: Set timezone to Asia/Singapore
        uses: szenius/set-timezone@v2.0
        with:
          timezoneLinux: "Europe/Moscow"
      - name: Checkout sources
        uses: actions/checkout@v6
      - name: Install sing-box
        run: curl -fsSL https://sing-box.app/install.sh | sh
      - name: Compile domains.srs
        run: sing-box rule-set compile --output domains.srs domains.json
      - name: Compile subnets.srs
        run: sing-box rule-set compile --output subnets.srs subnets.json
      - name: Set up variables
        id: vars
        run: |
          echo "date_now=$(date +"%Y-%m-%d %T")" >> "${GITHUB_OUTPUT}"
      - name: Upload files to Releases
        uses: ncipollo/release-action@v1
        with:
          makeLatest: true
          allowUpdates: true
          artifactErrorsFailBuild: true
          artifacts: ./*.srs
          body: |
            - Last build date: `${{steps.vars.outputs.date_now}}`
            - Reference commit: ${{github.sha}}
          name: Updatable rule sets
          removeArtifacts: true
          tag: updatable-rule-sets
