name: Development build

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  linux-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v6
      - name: Install sing-box
        run: curl -fsSL https://sing-box.app/install.sh | sh
      - name: Compile domains.srs
        run: sing-box rule-set compile --output domains.srs domains.json
      - name: Compile subnets.srs
        run: sing-box rule-set compile --output subnets.srs subnets.json
      - name: Set up variables
        id: vars
        run: echo "date_now=$(date +"%Y_%m_%d_%H_%M_%S")" >> "${GITHUB_OUTPUT}"
      - name: Upload files to Releases
        uses: ncipollo/release-action@v1
        with:
          makeLatest: true
          allowUpdates: true
          artifactErrorsFailBuild: true
          artifacts: ./*.srs
          body: |
            - Last build date: `${{steps.vars.outputs.date_now}}`
            - Reference commit: ${{github.sha}}
          name: Updatable rule sets
          removeArtifacts: true
          tag: updatable-rule-sets
      - name: Delete older releases
        uses: dev-drprasad/delete-older-releases@v1.2.0
        with:
          keep_latest: 5
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
